### ISSUE TITLE
Devices without /dev/radio0

### ISSUE THREAD

**Issue by kenOfYugen** [iusmac/RevampedFMRadio#8]
Hello @iusmac 
I was wondering how hard it would be to add support for devices that do not expose `/dev/radio0`.
For example, I believe that my Redmi Note 11 uses BT HCI access.
Have you stumbled upon information on how such devices work?

**Comment by iusmac** [comment]
Yeah, spes (and all newer devices) is shipped with the cherokee BT soc (`getprop vendor.qcom.bluetooth.soc`). Here, we only support all other BT chips, which are also a bit old.

You can discover everything you need [here](https://github.com/LineageOS/android_vendor_qcom_opensource_fm-commonsys) on how the communication is established through a HAL and how commands are piped using the vendor BT interface. At the end you still have to go through a /dev/smdX to which the BT soc is bound.

Whether it's hard or not, probably not that much since the core backend is already written, but it will definitely require some effort to port all the JNI libraries needed to establish the communication depending on soc.

**Comment by kenOfYugen** [comment]
Thanks, I really appreciate it.

**Comment by OothecaPickle** [comment]
I have a OnePlus Nord N200 5G (`dre`) running LineageOS.
My Bluetooth SoC's codename is `hastings` according to `vendor/build.prop` extracted from stock firmware.
I'd really like to use this app instead of [com.caf.fmradio](https://github.com/LineageOS/android_vendor_qcom_opensource_fm-commonsys/tree/lineage-22.2/fmapp2).

Any updates on adding support for devices with newer qcom BT SoCs (cherokee, hastings) and no `/dev/radio0`?

relevant logcat:
```
09-15 03:30:55.467 12339 12360 E android_hardware_fm: open_dev failed, [fd=-1] /dev/radio0
09-15 03:30:55.467 12339 12360 D android_hardware_fm: OpenFd, [ret=-1]
09-15 03:30:55.467 12339 12360 I android_hardware_fm: TurnOn, [freq=100]
09-15 03:30:55.467 12339 12360 I android_hardware_fm: Pwr_Up,[freq=100000]
09-15 03:30:55.467 12339 12360 D android_hardware_fm: BT soc is 'hastings'
09-15 03:30:55.467 12339 12360 E android_hardware_fm: open_dev failed, [fd=-1] /dev/radio0
09-15 03:30:55.467 12339 12360 E android_hardware_fm: Dev open failed
09-15 03:30:55.467 12339 12360 D android_hardware_fm: TurnOn, [ret=-1]
```

Would adding `vendor.hw.fm.init=0` (or `vendor.hw.fm.init=1`) to my vendor.prop make any difference?
